"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertCircle, BarChart3, CheckCircle2, Moon, RefreshCw, SlidersHorizontal, TrendingDown, TrendingUp } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

type Item = { id: string; name: string; energyKwh: string };
type Daily = { date: string; actualKwh: string | null; devicesKwh: string; coveredHours: number; completedHours: number };
type HeatCell = { date: string; hour: number; actualKwh: string | null; devicesKwh: string; quality: string; status: string };
type AnalyticsData = {
  from: string; to: string; settings: { currencyCode: string };
  summary: { actualKwh: string; devicesKwh: string; coveragePercent: number; completedHours: number; coveredHours: number; incomplete: boolean; actualCost: string | null };
  daily: Daily[]; heatmap: HeatCell[]; options: { devices: Item[]; categories: Item[]; zones: Item[] };
  byDevice: Item[]; byCategory: Item[]; byZone: Item[];
  night: { from: number; to: number; actualKwh: string; devicesKwh: string; sharePercent: number | null };
  compare: { from: string; to: string; actualKwh: string; devicesKwh: string; actualChangePercent: number | null; categoryContribution: Array<Item & { previousEnergyKwh: string; changeKwh: number }> };
  errors: string[];
};

const fieldClass = "h-10 rounded-xl border border-[#d8e3e7] bg-white px-3 text-sm text-[#17374c] outline-none focus:border-[#1e7680] focus:ring-2 focus:ring-[#1e7680]/20";
function addDays(date: string, amount: number) { const value = new Date(`${date}T12:00:00Z`); value.setUTCDate(value.getUTCDate() + amount); return value.toISOString().slice(0, 10); }
function energy(value: string | number | null) { return value === null ? "—" : Number(value).toLocaleString("ru-RU", { maximumFractionDigits: 3 }); }
function dateLabel(date: string) { return new Intl.DateTimeFormat("ru-RU", { day: "2-digit", month: "2-digit" }).format(new Date(`${date}T12:00:00Z`)); }
function money(value: string | null, currency: string) { return value === null ? "—" : new Intl.NumberFormat("ru-RU", { style: "currency", currency, maximumFractionDigits: 2 }).format(Number(value)); }

export function AnalyticsPage() {
  const today = useMemo(() => new Date().toISOString().slice(0, 10), []);
  const [from, setFrom] = useState(addDays(today, -29));
  const [to, setTo] = useState(today);
  const [quality, setQuality] = useState("ALL");
  const [device, setDevice] = useState("");
  const [category, setCategory] = useState("");
  const [zone, setZone] = useState("");
  const [data, setData] = useState<AnalyticsData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const requestId = useRef(0);
  const load = useCallback(async () => {
    const current = ++requestId.current; setLoading(true); setError("");
    const params = new URLSearchParams({ from, to, quality });
    if (device) params.set("devices", device); if (category) params.set("categories", category); if (zone) params.set("zones", zone);
    try { const response = await fetch(`/api/analytics?${params}`, { cache: "no-store" }); const body = await response.json() as AnalyticsData & { error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message || "Не удалось загрузить аналитику"); if (current === requestId.current) setData(body); }
    catch (requestError) { if (current === requestId.current) setError(requestError instanceof Error ? requestError.message : "Не удалось загрузить аналитику"); }
    finally { if (current === requestId.current) setLoading(false); }
  }, [from, to, quality, device, category, zone]);
  useEffect(() => { void load(); }, [load]);
  const chart = data?.daily.map(day => ({ ...day, label: dateLabel(day.date), actual: day.actualKwh === null ? undefined : Number(day.actualKwh), model: Number(day.devicesKwh) })) ?? [];
  const totalDevices = Number(data?.summary.devicesKwh ?? 0); const maxEnergy = Math.max(1, ...(data?.byDevice.map(item => Number(item.energyKwh)) ?? [1]));

  return <>
    <div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="mb-2 text-sm font-medium text-[#6e838e]">Динамика потребления</p><h1 className="text-[clamp(2rem,4vw,3.15rem)] font-semibold tracking-[-0.055em] text-[#102d43]">Аналитика</h1></div><Button variant="outline" className="rounded-xl" onClick={() => void load()} disabled={loading}><RefreshCw size={16} className={loading ? "animate-spin" : ""} />Обновить</Button></div>
    <Filters from={from} to={to} setFrom={setFrom} setTo={setTo} quality={quality} setQuality={setQuality} device={device} setDevice={setDevice} category={category} setCategory={setCategory} zone={zone} setZone={setZone} options={data?.options} />
    {error && <div className="mb-4 flex items-center justify-between rounded-2xl border border-[#efc7bd] bg-[#fff4f1] p-4 text-sm text-[#8c3f2c]" role="alert"><span className="flex items-center gap-2"><AlertCircle size={17} />{error}</span><Button variant="outline" size="sm" onClick={() => void load()}>Повторить</Button></div>}
    {loading && !data && <div className="surface-card grid min-h-52 place-items-center text-sm text-[#718590]">Загружаем аналитику…</div>}
    {data && <>
      {data.summary.incomplete && <div className="mb-4 flex items-center gap-3 rounded-2xl border border-[#f1d49f] bg-[#fff7e7] p-4 text-sm text-[#90600d]"><SlidersHorizontal size={17} />Итог неполный: учтено {data.summary.completedHours} завершённых часов, факт есть для {data.summary.coveredHours}.</div>}
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={BarChart3} label="Факт" value={`${energy(data.summary.actualKwh)} кВт⋅ч`} detail={money(data.summary.actualCost, data.settings.currencyCode)} /><Metric icon={TrendingUp} label="По приборам" value={`${energy(data.summary.devicesKwh)} кВт⋅ч`} detail={`${data.byDevice.length} приборов в выборке`} /><Metric icon={CheckCircle2} label="Покрытие" value={`${data.summary.coveragePercent.toLocaleString("ru-RU", { maximumFractionDigits: 1 })} %`} detail={`${data.summary.coveredHours} из ${data.summary.completedHours} часов`} progress={data.summary.coveragePercent} /><Metric icon={Moon} label="Ночная нагрузка" value={`${energy(data.night.actualKwh)} кВт⋅ч`} detail={`${data.night.from}:00–${data.night.to}:00 · ${data.night.sharePercent === null ? "—" : `${data.night.sharePercent.toLocaleString("ru-RU", { maximumFractionDigits: 1 })} % факта`}`} /></div>
      <div className="surface-card mt-4 p-5 sm:p-6"><div className="flex items-start justify-between"><div><h2 className="section-title">Факт и модель по дням</h2><p className="mt-1 text-sm text-[#738792]">Завершённые часы периода {from} — {to}</p></div><Badge variant="outline">Почасовые данные</Badge></div><div className="mt-5 h-[280px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{ top: 10, right: 8, left: -18, bottom: 0 }}><CartesianGrid vertical={false} stroke="#e6ecef" strokeDasharray="3 5" /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: "#748996", fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "#8a9aa4", fontSize: 11 }} /><Tooltip formatter={(value, name) => [`${energy(Number(value))} кВт⋅ч`, name === "actual" ? "Факт" : "Приборы"]} /><Area type="monotone" dataKey="actual" stroke="#173f5f" strokeWidth={3} fill="#173f5f" fillOpacity={0.1} connectNulls={false} /><Area type="monotone" dataKey="model" stroke="#d49424" strokeWidth={2} strokeDasharray="6 5" fill="transparent" /></AreaChart></ResponsiveContainer></div></div>
      <Tabs defaultValue="devices" className="mt-4"><TabsList><TabsTrigger value="devices">Приборы</TabsTrigger><TabsTrigger value="categories">Категории</TabsTrigger><TabsTrigger value="zones">Зоны</TabsTrigger><TabsTrigger value="heatmap">Тепловая карта</TabsTrigger><TabsTrigger value="compare">Сравнение</TabsTrigger></TabsList><TabsContent value="devices"><div className="surface-card p-5"><h2 className="section-title">Потребление по приборам</h2><div className="mt-5 grid gap-4">{data.byDevice.length ? data.byDevice.map(item => <div key={item.id}><div className="mb-1 flex justify-between gap-3 text-sm"><span>{item.name}</span><strong>{energy(item.energyKwh)} кВт⋅ч</strong></div><Progress value={Number(item.energyKwh) / maxEnergy * 100} className="h-2 bg-[#e5edef] [&>div]:bg-[#1e7680]" /></div>) : <Empty />}</div></div></TabsContent><TabsContent value="categories"><Breakdown items={data.byCategory} total={totalDevices} /></TabsContent><TabsContent value="zones"><Breakdown items={data.byZone} total={totalDevices} /></TabsContent><TabsContent value="heatmap"><Heatmap cells={data.heatmap} /></TabsContent><TabsContent value="compare"><Compare data={data.compare} /></TabsContent></Tabs>
    </>}
  </>;
}

function Filters({ from, to, setFrom, setTo, quality, setQuality, device, setDevice, category, setCategory, zone, setZone, options }: { from: string; to: string; setFrom: (value: string) => void; setTo: (value: string) => void; quality: string; setQuality: (value: string) => void; device: string; setDevice: (value: string) => void; category: string; setCategory: (value: string) => void; zone: string; setZone: (value: string) => void; options?: AnalyticsData["options"] }) { return <div className="surface-card mb-4 grid gap-3 p-4 md:grid-cols-3 xl:grid-cols-6"><label className="grid gap-1 text-xs font-medium text-[#637b89]">С<input className={fieldClass} type="date" value={from} onChange={event => setFrom(event.target.value)} /></label><label className="grid gap-1 text-xs font-medium text-[#637b89]">По<input className={fieldClass} type="date" value={to} onChange={event => setTo(event.target.value)} /></label><Select label="Прибор" value={device} setValue={setDevice} items={options?.devices} all="Все приборы" /><Select label="Категория" value={category} setValue={setCategory} items={options?.categories} all="Все категории" /><Select label="Зона" value={zone} setValue={setZone} items={options?.zones} all="Все зоны" /><label className="grid gap-1 text-xs font-medium text-[#637b89]">Качество<select className={fieldClass} value={quality} onChange={event => setQuality(event.target.value)}><option value="ALL">Все часы</option><option value="EXACT">Точное</option><option value="INTERPOLATED">Интерполяция</option><option value="MANUAL">Ручное</option><option value="MISSING">Нет факта</option></select></label></div>; }
function Select({ label, value, setValue, items, all }: { label: string; value: string; setValue: (value: string) => void; items?: Item[]; all: string }) { return <label className="grid gap-1 text-xs font-medium text-[#637b89]">{label}<select className={fieldClass} value={value} onChange={event => setValue(event.target.value)}><option value="">{all}</option>{items?.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>; }
function Metric({ icon: Icon, label, value, detail, progress }: { icon: typeof BarChart3; label: string; value: string; detail: string; progress?: number }) { return <div className="surface-card p-5"><Icon size={18} className="text-[#1e7680]" /><p className="eyebrow mt-4">{label}</p><p className="mt-2 text-2xl font-semibold text-[#14364b]">{value}</p><p className="mt-1 text-sm text-[#718590]">{detail}</p>{progress !== undefined && <Progress value={progress} className="mt-3 h-2 bg-[#e5edef] [&>div]:bg-[#2b937b]" />}</div>; }
function Breakdown({ items, total }: { items: Item[]; total: number }) { return <div className="surface-card p-5"><h2 className="section-title">Распределение</h2><div className="mt-5 grid gap-4">{items.length ? items.map(item => { const value = Number(item.energyKwh); return <div key={item.id}><div className="mb-1 flex justify-between text-sm"><span>{item.name}</span><strong>{energy(item.energyKwh)} кВт⋅ч · {total ? (value / total * 100).toLocaleString("ru-RU", { maximumFractionDigits: 1 }) : 0} %</strong></div><Progress value={total ? value / total * 100 : 0} className="h-2 bg-[#e5edef] [&>div]:bg-[#1e7680]" /></div>; }) : <Empty />}</div></div>; }
function Heatmap({ cells }: { cells: HeatCell[] }) { const days = Array.from(new Set(cells.map(cell => cell.date))); const bySlot = new Map(cells.map(cell => [`${cell.date}:${cell.hour}`, cell])); return <div className="surface-card overflow-x-auto p-5"><h2 className="section-title">День × час</h2><div className="mt-4 min-w-[820px]"><div className="grid grid-cols-[90px_repeat(24,minmax(22px,1fr))] gap-1 text-[10px] text-[#718590]"><span />{Array.from({ length: 24 }, (_, hour) => <span className="text-center" key={hour}>{hour}</span>)}{days.map(date => <div className="contents" key={date}><a className="self-center text-xs font-medium text-[#536d7b]" href={`/reconciliation?from=${date}&to=${date}`}>{dateLabel(date)}</a>{Array.from({ length: 24 }, (_, hour) => <HeatSquare cell={bySlot.get(`${date}:${hour}`)} date={date} hour={hour} key={`${date}-${hour}`} />)}</div>)}</div></div></div>; }
function HeatSquare({ cell, date, hour }: { cell?: HeatCell; date: string; hour: number }) { const value = Number(cell?.actualKwh ?? cell?.devicesKwh ?? 0); return <a className="h-6 rounded-sm border border-white" href={`/reconciliation?from=${date}&to=${date}&hour=${hour}#hour-${hour}`} aria-label={`${date}, ${hour}:00`} title={`${date} ${hour}:00 · ${energy(cell?.actualKwh ?? cell?.devicesKwh ?? null)} кВт⋅ч`} style={{ backgroundColor: cell?.quality === "MISSING" ? "#f4d4cc" : `rgba(30,118,128,${Math.max(.12, Math.min(1, value / 20))})` }} />; }
function Compare({ data }: { data: AnalyticsData["compare"] }) { return <div className="surface-card p-5"><div className="flex items-center gap-3"><TrendingDown className={data.actualChangePercent !== null && data.actualChangePercent > 0 ? "rotate-180 text-[#b66b18]" : "text-[#2b937b]"} /><div><h2 className="section-title">{data.from} — {data.to}</h2><p className="mt-1 text-sm text-[#738792]">Сравнение факта с текущим периодом</p></div></div><p className="mt-5 text-4xl font-semibold text-[#102d43]">{data.actualChangePercent === null ? "—" : `${data.actualChangePercent >= 0 ? "+" : ""}${data.actualChangePercent.toLocaleString("ru-RU", { maximumFractionDigits: 1 })} %`}</p><p className="mt-1 text-sm text-[#6f838e]">Предыдущий факт: {energy(data.actualKwh)} кВт⋅ч</p><div className="mt-6 grid gap-3">{data.categoryContribution.map(item => <div className="flex justify-between border-b border-[#e7edef] pb-2 text-sm" key={item.id}><span>{item.name}</span><span className={item.changeKwh >= 0 ? "text-[#a66b0a]" : "text-[#2b806f]"}>{item.changeKwh >= 0 ? "+" : ""}{energy(item.changeKwh)} кВт⋅ч</span></div>)}</div></div>; }
function Empty() { return <p className="py-8 text-center text-sm text-[#718590]">Нет данных для выбранных фильтров.</p>; }
